parameters:
  name: 'webdrivermanager'
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 60
  cancelTimeoutInMinutes: 25
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python27:
        os_name:  ${{ parameters.name }}
        python_version: '2.7'
      Python37:
        os_name:  ${{ parameters.name }}
        python_version: '3.7'
    maxParallel: 2

  steps:
  - task: UsePythonVersion@0
    displayName: 'Python for test execution'
    inputs:
      versionSpec: $(python_version)
      addToPath: true
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      python -m pip install -r requirements-dev.txt
    displayName: 'Install requirements'

  - script: python test/test_acceptance.py
    displayName: 'Running Acceptance Tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: acceptance_tests.xml
      testResultsTitle: Acceptance Results for $(os_name) with Python $(python_version)
      testRunTitle: Python-$(python_version)-$(os_name)-acceptance

  - script: |
      flake8 --output flake8.txt
      flake8_junit flake8.txt flake8.xml
      cat flake8.xml
      pylint webdrivermanager/ tests/ c --exit-zero --output-format=pylint2junit.JunitReporter > pylint.xml
    displayName: 'Running Static Analysis'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: flake8.xml
      testResultsTitle: Flake8 Results for $(os_name) with Python $(python_version)
      testRunTitle: Python-$(python_version)-$(os_name)-flake8

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: pylint.xml
      testResultsTitle: PyLint Results for $(os_name) with Python $(python_version)
      testRunTitle: Python-$(python_version)-$(os_name)-pylint

  - script: python setup.py sdist
    displayName: 'Generate sdist files'
